# PACKAGE_PIN
set_property PACKAGE_PIN U13 [get_ports {ans[7]}]
set_property PACKAGE_PIN K2 [get_ports {ans[6]}]
set_property PACKAGE_PIN T14 [get_ports {ans[5]}]
set_property PACKAGE_PIN P14 [get_ports {ans[4]}]
set_property PACKAGE_PIN J14 [get_ports {ans[3]}]
set_property PACKAGE_PIN T9 [get_ports {ans[2]}]
set_property PACKAGE_PIN J18 [get_ports {ans[1]}]
set_property PACKAGE_PIN J17 [get_ports {ans[0]}]
set_property PACKAGE_PIN T10 [get_ports {seg[6]}]
set_property PACKAGE_PIN R10 [get_ports {seg[5]}]
set_property PACKAGE_PIN K16 [get_ports {seg[4]}]
set_property PACKAGE_PIN K13 [get_ports {seg[3]}]
set_property PACKAGE_PIN P15 [get_ports {seg[2]}]
set_property PACKAGE_PIN T11 [get_ports {seg[1]}]
set_property PACKAGE_PIN L18 [get_ports {seg[0]}]

# sigs - 从左到右
set_property PACKAGE_PIN V11 [get_ports memtoreg]
set_property PACKAGE_PIN V12 [get_ports memwrite]
set_property PACKAGE_PIN V14 [get_ports pcsrc]
set_property PACKAGE_PIN V15 [get_ports alusrc]
set_property PACKAGE_PIN T16 [get_ports regdst]
set_property PACKAGE_PIN U14 [get_ports regwrite]
set_property PACKAGE_PIN T15 [get_ports jump]
set_property PACKAGE_PIN V16 [get_ports branch]
set_property PACKAGE_PIN U16 [get_ports {alu_control[2]}]
set_property PACKAGE_PIN U17 [get_ports {alu_control[1]}]
set_property PACKAGE_PIN V17 [get_ports {alu_control[0]}]

# input
set_property PACKAGE_PIN E3 [get_ports Mhz]
set_property PACKAGE_PIN N17 [get_ports rst]
set_property PACKAGE_PIN V10 [get_ports RST]



# IOSTANDARD
set_property IOSTANDARD LVCMOS33 [get_ports alusrc]
set_property IOSTANDARD LVCMOS33 [get_ports branch]
set_property IOSTANDARD LVCMOS33 [get_ports jump]
set_property IOSTANDARD LVCMOS33 [get_ports memtoreg]
set_property IOSTANDARD LVCMOS33 [get_ports memwrite]
set_property IOSTANDARD LVCMOS33 [get_ports regwrite]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports Mhz]
set_property IOSTANDARD LVCMOS33 [get_ports regdst]
set_property IOSTANDARD LVCMOS33 [get_ports {alu_control[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {alu_control[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {alu_control[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ans[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ans[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ans[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ans[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ans[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ans[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ans[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ans[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports RST]
set_property IOSTANDARD LVCMOS33 [get_ports pcsrc]
